src/main/resources/application.properties
server.port=8081
spring.application.name=MS_INVENTARIO

# ── CONEXION A ORACLE ─────────────────────────────────
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
# Si no funciona con XE, prueba:
# spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=MS_INVENTARIO
spring.datasource.password=Pass1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── JPA / HIBERNATE ───────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.root=INFO
logging.level.com.ecommerce=DEBUG
spring.jackson.serialization.indent-output=true

# ── HIKARI (limitar conexiones para Oracle XE) ────────
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000